https://medium.com/analytics-vidhya/use-naive-bayes-algorithm-for-categorical-and-numerical-data-classification-935d90ab273f

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

In [3]:
print("Number of mislabeled points out of a total %d points : %d"
      % (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 75 points : 4


30/12/2022

In [2]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,roc_curve
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [7]:
x = data.drop(['Outcome'],axis=1)
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [8]:
y = data.Outcome
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [10]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size=.25,random_state=30)

In [13]:
naive_bayes=GaussianNB()
naive_bayes.fit(x_train,y_train)


GaussianNB()

In [15]:
y_pred = naive_bayes.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [16]:
naive_bayes.score(x_test,y_test)

0.7916666666666666

### Dataset for Naive_Bayes or Natural Language Processing
12/12/2022

In [4]:
#Spam classification 
import pandas as pd 
df = pd.read_csv("https://raw.githubusercontent.com/sunnysavita10/Naive-Bayes/main/SpamClassifier-with-ML/sms_spam_data/SMSSpamCollection.csv",sep="\t",header=None,names=["label","messages"])
df.head()

label                                           messages
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df["messages"][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [6]:
df["messages"][78]

'Does not operate after  &lt;#&gt;  or what'

In [7]:
df["messages"][2764]

'Say this slowly.? GOD,I LOVE YOU &amp; I NEED YOU,CLEAN MY HEART WITH YOUR BLOOD.Send this to Ten special people &amp; u c miracle tomorrow, do it,pls,pls do it...'

In [8]:
df['messages'].loc[451]

'hanks lotsly!'

In [9]:
df.shape

(5572, 2)

In [10]:
df.columns

Index(['label', 'messages'], dtype='object')

In [11]:
df.describe()

label                messages
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [12]:
#Data Cleaning and Preprocessing
import nltk
import re # Regular Expression

In [13]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [14]:
from nltk.corpus import stopwords

In [15]:
from nltk.stem.porter import PorterStemmer

In [16]:
ps=PorterStemmer()

In [17]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [18]:
review=re.sub('[^a-zA-Z]',' ',df["messages"][10])
review


'I m gonna be home soon and i don t want to talk about this stuff anymore tonight  k  I ve cried enough today '

In [19]:
review=review.lower()
review

'i m gonna be home soon and i don t want to talk about this stuff anymore tonight  k  i ve cried enough today '

In [20]:
review=review.split()
review


['i',
 'm',
 'gonna',
 'be',
 'home',
 'soon',
 'and',
 'i',
 'don',
 't',
 'want',
 'to',
 'talk',
 'about',
 'this',
 'stuff',
 'anymore',
 'tonight',
 'k',
 'i',
 've',
 'cried',
 'enough',
 'today']

In [21]:
review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
review


['gonna',
 'home',
 'soon',
 'want',
 'talk',
 'stuff',
 'anymor',
 'tonight',
 'k',
 'cri',
 'enough',
 'today']

In [22]:
review=''.join(review)
review

'gonnahomesoonwanttalkstuffanymortonightkcrienoughtoday'

In [23]:
corpus=[]

In [24]:
for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z]',' ',df["messages"][i])
    review=review.lower()
    review=review.split()
    
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [25]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [26]:
corpus[0:3000]

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [27]:
len(corpus)

5572

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,binary=True,ngram_range=(2,2))

In [29]:
X=cv.fit_transform(corpus).toarray()

In [30]:
#1. Set of unique words 
#2. finally it is creating a vector 
X.shape

(5572, 2500)

In [31]:
len(X[0])

2500

In [32]:
X[4998] - X[4967]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
df['label']

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [34]:
y=pd.get_dummies(df['label'])#,drop_first=True)
y=y.iloc[:,1].values

In [35]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

In [40]:
y_pred=gnb.predict(X_test)

In [41]:
from sklearn.metrics import accuracy_score

In [42]:
accuracy_score(y_test,y_pred)

0.5398420674802584

In [43]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.48      0.99      0.64       590
           1       0.96      0.21      0.35       803

    accuracy                           0.54      1393
   macro avg       0.72      0.60      0.50      1393
weighted avg       0.75      0.54      0.47      1393



### Bag of Words

In [44]:
from sklearn.naive_bayes import MultinomialNB

In [45]:
model2=MultinomialNB()

In [46]:
model2.fit(X_train,y_train)

MultinomialNB()

In [47]:
y_pred2=model2.predict(X_test)

In [48]:
accuracy_score(y_test,y_pred2)

0.9662598707824839

In [49]:
from sklearn.metrics import classification_report
print(classification_report(y_pred2,y_test))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98      1260
           1       0.74      0.99      0.85       133

    accuracy                           0.97      1393
   macro avg       0.87      0.98      0.91      1393
weighted avg       0.97      0.97      0.97      1393



### Creating the TFIDF model

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500)
X = tv.fit_transform(corpus)
X.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [51]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [52]:
from sklearn.naive_bayes import MultinomialNB

In [53]:
model3=MultinomialNB()

In [54]:
model3.fit(X_train,y_train)

MultinomialNB()

In [55]:
y_pred3=model3.predict(X_test)

In [56]:
accuracy_score(y_test,y_pred3)

0.9741564967695621

In [57]:
from sklearn.metrics import classification_report
print(classification_report(y_pred3,y_test))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99      1249
           1       0.80      0.99      0.89       144

    accuracy                           0.97      1393
   macro avg       0.90      0.98      0.94      1393
weighted avg       0.98      0.97      0.98      1393



In [58]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [59]:
y_pred4=classifier.predict(X_test)

In [60]:
accuracy_score(y_test,y_pred4)

0.9676956209619526

In [61]:
from sklearn.metrics import classification_report
print(classification_report(y_pred4,y_test))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98      1260
           1       0.75      1.00      0.86       133

    accuracy                           0.97      1393
   macro avg       0.87      0.98      0.92      1393
weighted avg       0.98      0.97      0.97      1393



### Word to Vector

In [62]:
df.head()

label                                           messages
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [63]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [64]:
corpus1 = []
for i in range(0, len(df)):
    review1 = re.sub('[^a-zA-Z]', ' ', df['messages'][i])
    review1 = review.lower()
    review1 = review.split()
    
    review1 = [lemmatizer.lemmatize(word) for word in review1 if not word in stopwords.words('english')]
    review1 = ' '.join(review1)
    corpus1.append(review1)

LookupError: 
**********************************************************************
  Resource omw-1.4 not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('omw-1.4')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/omw-1.4

  Searched in:
    - 'C:\\Users\\HP/nltk_data'
    - 'c:\\Python310\\nltk_data'
    - 'c:\\Python310\\share\\nltk_data'
    - 'c:\\Python310\\lib\\nltk_data'
    - 'C:\\Users\\HP\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [65]:
import gensim 
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [66]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [67]:
words

[['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entri',
  'wkli',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'st',
  'may',
  'text',
  'fa',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'appli'],
 ['dun', 'say', 'earli', 'hor', 'alreadi', 'say'],
 ['nah', 'think', 'goe', 'usf', 'live', 'around', 'though'],
 ['freemsg',
  'hey',
  'darl',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chg',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['winner',
  'valu',
  'network',
  'custom',
  'select',
  'receivea',
  'prize',
  'reward',
  

In [68]:
### Lets train Word2vec from scratch
model=gensim.models.Word2Vec(words,window=5,min_count=2)

In [69]:
model.wv.index_to_key

['call',
 'go',
 'get',
 'ur',
 'gt',
 'lt',
 'come',
 'day',
 'ok',
 'free',
 'know',
 'love',
 'like',
 'time',
 'want',
 'good',
 'got',
 'text',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'take',
 'stop',
 'see',
 'home',
 'think',
 'repli',
 'lor',
 'sorri',
 'still',
 'tell',
 'mobil',
 'back',
 'da',
 'dont',
 'make',
 'phone',
 'pleas',
 'week',
 'hi',
 'say',
 'work',
 'new',
 'later',
 'pl',
 'hope',
 'miss',
 'ask',
 'co',
 'msg',
 'min',
 'meet',
 'messag',
 'dear',
 'night',
 'happi',
 'wait',
 'well',
 'give',
 'thing',
 'tri',
 'great',
 'much',
 'oh',
 'claim',
 'wat',
 'hey',
 'number',
 'friend',
 'thank',
 'way',
 'ye',
 'www',
 'let',
 'prize',
 'feel',
 'right',
 'even',
 'tomorrow',
 'win',
 'pick',
 'alreadi',
 'tone',
 'care',
 'cash',
 'said',
 'amp',
 'im',
 'leav',
 'yeah',
 'realli',
 'find',
 'babe',
 'life',
 'morn',
 'last',
 'sleep',
 'keep',
 'uk',
 'year',
 'servic',
 'nokia',
 'sure',
 'anyth',
 'com',
 'buy',
 'use',
 'would',
 'start',
 'contact',

In [70]:
model.corpus_count

5564

In [71]:
model.epochs

5

In [72]:
model.wv.similar_by_word('kid')

[('amp', 0.9982840418815613),
 ('im', 0.9982835054397583),
 ('use', 0.9982776641845703),
 ('sleep', 0.9982388615608215),
 ('big', 0.9982367753982544),
 ('well', 0.9982141852378845),
 ('guess', 0.9982099533081055),
 ('make', 0.9982074499130249),
 ('one', 0.9982061386108398),
 ('last', 0.9982049465179443)]

In [89]:
model.wv.similar_by_word('love')

[('much', 0.9997926354408264),
 ('amp', 0.9997850060462952),
 ('one', 0.9997847676277161),
 ('need', 0.9997831583023071),
 ('hey', 0.9997585415840149),
 ('give', 0.9997574090957642),
 ('make', 0.9997564554214478),
 ('feel', 0.9997560381889343),
 ('hope', 0.999743640422821),
 ('day', 0.9997425079345703)]

In [73]:
model.wv['kid'].shape

(100,)

In [79]:
import numpy as np 
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [80]:
from tqdm import tqdm

In [81]:
words[73]

['perform']

In [82]:
type(model.wv.index_to_key)

list

In [90]:
#apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    #print("Hello",i)
    X.append(avg_word2vec(words[i]))

100%|██████████| 5564/5564 [00:00<00:00, 5979.70it/s]


In [91]:
type(X)

list

In [92]:
X_new=np.array(X)

C:\Users\HP\AppData\Local\Temp\ipykernel_11680\3504696623.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_new=np.array(X)


In [93]:
X_new[3]

array([-0.27210435,  0.32680228,  0.05433524, -0.00279693,  0.08853537,
       -0.5395765 ,  0.12118568,  0.64065385, -0.22674303, -0.22917782,
       -0.1390058 , -0.45845962, -0.11676677,  0.05917332,  0.10824866,
       -0.20722038,  0.05286913, -0.400358  ,  0.02146888, -0.67444134,
        0.24410428,  0.18788612,  0.07685416, -0.10218704, -0.14194894,
        0.04023622, -0.28921506, -0.30244228, -0.23381509,  0.1297342 ,
        0.34385666,  0.08394892,  0.0569012 , -0.18999742, -0.21725178,
        0.33933055, -0.10673866, -0.25060943, -0.05030724, -0.530463  ,
        0.10086608, -0.27813783, -0.06589725,  0.09235444,  0.25362223,
       -0.15632468, -0.186426  , -0.02558683,  0.21486115,  0.29209128,
        0.05116994, -0.28587854, -0.10446583,  0.02283641, -0.24009828,
        0.1664085 ,  0.16829522, -0.00933325, -0.3727013 ,  0.06917316,
        0.06976131,  0.24299233, -0.18200141, -0.11175277, -0.37898088,
        0.1845939 ,  0.1618158 ,  0.22706485, -0.27617204,  0.38

In [94]:
X_new.shape

(5564,)

In [95]:
X_new[0].shape

(100,)

In [96]:
words[0]

['go',
 'jurong',
 'point',
 'crazi',
 'avail',
 'bugi',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amor',
 'wat']

In [97]:
words[1]

['ok', 'lar', 'joke', 'wif', 'oni']

In [98]:
X_new

array([array([-0.220572  ,  0.26374093,  0.04693029,  0.00508847,  0.07051784,
              -0.43307194,  0.09364337,  0.5166647 , -0.1922297 , -0.18922621,
              -0.11366708, -0.36962283, -0.09143785,  0.05035512,  0.0894709 ,
              -0.1661511 ,  0.03925844, -0.31930205,  0.02038653, -0.5435515 ,
               0.19486742,  0.15206529,  0.06535112, -0.07868215, -0.11374781,
               0.03537482, -0.2337283 , -0.24428682, -0.18775535,  0.10768101,
               0.27581128,  0.06424174,  0.04894345, -0.15364043, -0.1733554 ,
               0.27649212, -0.07739136, -0.19927414, -0.04454878, -0.42142263,
               0.07929174, -0.22293647, -0.05957735,  0.07981256,  0.20357893,
              -0.1246505 , -0.14916314, -0.02510239,  0.17375183,  0.23487693,
               0.0392792 , -0.23186739, -0.08390582,  0.01810476, -0.18663113,
               0.1344018 ,  0.13211147, -0.00881386, -0.2979302 ,  0.0529225 ,
               0.05631549,  0.19850616, -0.15205958,

https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

https://colah.github.io/posts/2015-08-Understanding-LSTMs/